backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

# This line should be uncommented and pointed to your media folder
media_folder: "src/images/uploads"

# This line should be uncommented and pointed to your media folder
public_folder: "/images/uploads"

collections:
  # This is the original collection for blog posts
  - name: "posts"
    label: "Posts"
    folder: "src/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Tags", name: "tags", widget: "list", default: ["post"]}
      - {label: "Layout", name: "layout", widget: "hidden", default: "layouts/post.njk"}
      - {label: "Body", name: "body", widget: "markdown"}

  # This is the new collection you are adding for static pages
  - name: "pages"
    label: "Pages"
    folder: "src/pages"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Permalink", name: "permalink", widget: "string", hint: "The URL for your page. Must start and end with a slash, e.g., /about/"}
      - {label: "Layout", name: "layout", widget: "hidden", default: "layouts/page.njk"}
      - {label: "Body", name: "body", widget: "markdown"}
