backend:
  name: git-gateway
  branch: main

media_folder: "static/img/uploads"
public_folder: "/img/uploads"

collections:
  - name: "demos"
    label: "Demos"
    folder: "demos"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Script URL", name: "scriptUrl", widget: "string"}
      - {label: "Layout", name: "layout", widget: "hidden", default: "layouts/demo.njk"}
      - {label: "Tags", name: "tags", widget: "hidden", default: ["demo"]}
