# ===================================================================
# Backend Configuration
# This tells the CMS how to connect to your GitHub repository.
# ===================================================================
backend:
  name: git-gateway
  # IMPORTANT: Replace "main" below with your actual default branch
  # name you found in Part A (it's probably "main" or "master").
  branch: main

# ===================================================================
# Media and Public Folder Configuration
# This tells the CMS where to save uploaded images.
# ===================================================================
media_folder: "src/images/uploads"
public_folder: "/images/uploads"

# ===================================================================
# Collections Configuration
# This defines the content types for your site (Posts and Pages).
# ===================================================================
collections:
  # Collection for Blog Posts
  - name: "posts"
    label: "Posts"
    folder: "src/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Tags", name: "tags", widget: "list", default: ["post"]}
      - {label: "Layout", name: "layout", widget: "hidden", default: "layouts/post.njk"}
      - {label: "Body", name: "body", widget: "markdown"}

  # Collection for Static Pages (About, Contact, etc.)
  - name: "pages"
    label: "Pages"
    folder: "src/pages"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Permalink", name: "permalink", widget: "string", hint: "The URL for your page. Must start and end with a slash, e.g., /about/"}
      - {label: "Layout", name: "layout", widget: "hidden", default: "layouts/page.njk"}
      - {label: "Body", name: "body", widget: "markdown"}
