  - name: "demos"
    label: "Demos"
    folder: "demos" # We'll save these in a new "demos" folder
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string", hint: "The name of your project or demo."}
      - {label: "Script URL", name: "scriptUrl", widget: "string", hint: "The full URL to the demo you want to embed."}
      - {label: "Layout", name: "layout", widget: "hidden", default: "layouts/demo.njk"}
      - {label: "Tags", name: "tags", widget: "hidden", default: ["demo"]}
